version: 2
updates:
  - package-ecosystem: npm
    directory: '/site'
    schedule:
      interval: daily
      time: '04:00'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
