osx_image: xcode11
os: osx
language: node_js
node_js: node

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  npm: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test || travis_terminate 1
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run build

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

notifications:
  email: false
